# The URL the site will be built for
base_url = "https://basszhattyuk.github.io/org-portal/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

title = "Basszhattyúk Vezetőség"
theme = "tabi"

default_language = "hu"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "css"

[extra]
# Put all your custom variables here
skin = "red"
favicon = "img/icons/favicon2.ico"

menu = [
    { name = "Felelősok", url = "2026/responsibility", weight = 1 },
    { name = "Megbeszélések", url = "2026/meeting", weight = 2 },
]


remote_repository_url = "https://github.com/Basszhattyuk/org-portal"
remote_repository_git_platform = "auto"
remote_repository_branch = "main"
show_remote_changes = true
show_remote_source = true


socials = [
    { name = "github", url = "https://github.com/Basszhattyuk", icon = "github" },
    { name = "instagram", url = "https://www.instagram.com/basszhattyuk/", icon = "instagram" }
]

quick_navigation_buttons = true

[extra.giscus]
enabled_for_all_posts = true
automatic_loading = true
repo = "Basszhattyuk/org-portal"
repo_id = "R_kgDOQkE7Ig"
category = "Announcements"
category_id = "DIC_kwDOQkE7Is4CzgMW"
mapping = "slug"
strict_title_matching = 0
enable_reactions = 1
comment_box_above_comments = true
light_theme = "noborder_light"
dark_theme = "noborder_dark"
lang = "hu"
lazy_loading = true
